spring:
  application:
    name: schedulo

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
    jwt:
      secret: ${SPRING_SECURITY_JWT_SECRET}
      expiration-in-ms: 3600000 # 1h
